# config/models.yaml

gpt-4o-mini:
  provider: openai
  model: gpt-4o-mini
  api_key_env: OPENAI_API_KEY
  base_url: https://api.openai.com/v1

deepseek-chat:
  provider: deepseek
  model: deepseek-chat
  api_key_env: DEEPSEEK_API_KEY
  base_url: https://api.deepseek.com/v1

claude-3-opus:
  provider: anthropic
  model: claude-3-opus
  api_key_env: CLAUDE_API_KEY
  base_url: https://api.anthropic.com/v1
